impl
ZhNV2/jvm pull request #3
Opened 2017-10-01 14:46 UTC by ZhNV2

2017-10-07 20:05 UTC, adkozlov requested changes
Грубая ошибка проектирования: нарушение контракта интерфейса.

2017-10-07 20:05 UTC, adkozlov commented on src/test/scala/ru/spbau/zhidkov/MultiSetTest.scala
> +  def testAddNewElement(): Unit = assertEquals(MultiSet(1, 2, 3, 4), MultiSet(1, 2, 3) + 4)
Читать такой однострочный метод все же не очень удобно.
Плюс есть рекомендация не использовать бесскобочный синтаксис для процедур.

2017-10-07 20:05 UTC, adkozlov commented on src/main/scala/ru/spbau/zhidkov/MultiSet.scala
> +class MultiSet[T] (private val values: Map[T, Int] = Map.empty[T, Int]) extends SetLike[T, MultiSet[T]] with Set[T] {
Остается возможность вызывать публичный конструктор от объекта типа `Map`.
Почему нельзя тогда использовать любые другие типы коллекций.

2017-10-07 20:05 UTC, adkozlov commented on src/main/scala/ru/spbau/zhidkov/MultiSet.scala
> +  override def empty: MultiSet[T] = new MultiSet[T]
Можно обойтись без создания новой коллекции каждый раз.

2017-10-07 20:05 UTC, adkozlov commented on src/main/scala/ru/spbau/zhidkov/MultiSet.scala
> +  def apply[T](elems: T*): MultiSet[T] = MultiSet.empty ++ elems
Создание инстанса дважды?

2017-10-07 20:05 UTC, adkozlov commented on src/main/scala/ru/spbau/zhidkov/MultiSet.scala
> +    var multiSet: MultiSet[T] = MultiSet.empty
Публичное изменяемое свойство?

2017-10-07 20:05 UTC, adkozlov commented on src/main/scala/ru/spbau/zhidkov/MultiSet.scala
> +  implicit def canBuildFrom[A,B]: CanBuildFrom[MultiSet[B], A, MultiSet[A]] =
Не могли бы Вы пояснить, почему тайп-класс определяется именно таким образом?

2017-10-07 20:05 UTC, adkozlov commented on src/main/scala/ru/spbau/zhidkov/MultiSet.scala
> +class MultiSet[T] (private val values: Map[T, Int] = Map.empty[T, Int]) extends SetLike[T, MultiSet[T]] with Set[T] {
Формулировка задания действительно явно не запрещает наследование от стандартных коллекций. Сделано это по следующей причине: в стандартной библиотеке нет реализации мультимножества в чистом виде, а также интерфейсов для него.

Мультимножество не может использоваться в качестве множества по определению. Так как может содержать  эквивалентные объекты.
Ваша реализация может использоваться в качестве множества, и итератор возвращает одинаковые элементы. Что является грубым нарушением контракта интерфейса `Set`.

2017-10-08 10:30 UTC, ZhNV2 commented on src/main/scala/ru/spbau/zhidkov/MultiSet.scala
> +class MultiSet[T] (private val values: Map[T, Int] = Map.empty[T, Int]) extends SetLike[T, MultiSet[T]] with Set[T] {
То есть вообще нельзя получается от Set наследоваться?
Надо все переписать на просто мультмножество без наследования?

2017-10-28 11:56 UTC, closed without merging